const { execSync } = require("child_process")
const path = require("path")
const fs = require("fs")

// === Basic variables ===
const projectDir = process.cwd()
const srcDir = path.join(projectDir, "src")
const toolsDir = path.join(projectDir, "tools")

const folders = [
  "src/config",
  "src/core/middleware",
  "src/core/utils",
  "src/features",
  "tools"
]

// === Helper to run commands ===
const run = (cmd) => {
  console.log(`Running: ${cmd}`)
  execSync(cmd, { cwd: projectDir})
}

// === Initialize project ===
console.log("🔧 Initializing Express project...")

if (!fs.existsSync(path.join(projectDir, "package.json"))) {
  run("npm init -y")
} else {
  console.log("package.json exists — skipping npm init")
}

// === Install dependencies ===
if (!fs.existsSync(path.join(projectDir, "node_modules"))) {
  run("npm install express cors dotenv morgan")
} else {
  console.log("node_modules exist — skipping dependency install")
}

// === Update package.json ===
const pkgPath = path.join(projectDir, "package.json")
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"))

pkg.main = "src/server.js"
pkg.scripts = {
  dev: "node --watch src/server.js",
  models: "node tools/createModule.js",
  delete: "node tools/deleteModule.js"
}

fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2))
console.log("Updated package.json with scripts and entry point")

// === Create folders ===
folders.forEach(dir => {
  if (!fs.existsSync(path.join(projectDir, dir))) {
    fs.mkdirSync(path.join(projectDir, dir), { recursive: true })
    console.log(`Created folder: ${dir}`)
  }
})

// === .gitignore ===
const gitIgnorePath = path.join(projectDir, ".gitignore")
if (!fs.existsSync(gitIgnorePath)) {
  fs.writeFileSync(
    gitIgnorePath,
    `node_modules
.env
setUpExpress.js
`
  )
  console.log(".gitignore created")
}

// === app.js ===
const appJs = path.join(srcDir, "app.js")
if (!fs.existsSync(appJs)) {
  fs.writeFileSync(
    appJs,
`const express = require("express")
const app = express()

app.use(express.json())

// Example route
app.get("/", (req, res) => {
  res.send("Server running. Generated by setup script.")
})

module.exports = app
`
  )
  console.log("Created src/app.js")
}

// === server.js ===
const serverJs = path.join(srcDir, "server.js")
if (!fs.existsSync(serverJs)) {
  fs.writeFileSync(
    serverJs,
`const app = require("./app")
const PORT = process.env.PORT || 3000

app.listen(PORT, () => {
  console.log(\`Server listening on port \${PORT}\`)
})
`
  )
  console.log("Created src/server.js")
}

// === createModule.js ===
const createModuleTool = path.join(toolsDir, "createModule.js")
if (!fs.existsSync(createModuleTool)) {
  fs.writeFileSync(
    createModuleTool,
`const fs = require("fs")
const path = require("path")

const name = process.argv[2]
if (!name) {
  console.error("Please provide a feature name. Example: node tools/createModule.js user")
  process.exit(1)
}

const capitalized = name.charAt(0).toUpperCase() + name.slice(1)
const featureDir = path.join(process.cwd(), "src", "features", name)

if (!fs.existsSync(featureDir)) fs.mkdirSync(featureDir, { recursive: true })

const controllerContent = \`exports.getAll\${capitalized} = (req, res) => {
  res.send("Get all \${name}")
}\`

const routeContent = \`const express = require("express")
const router = express.Router()
const { getAll\${capitalized} } = require("./\${name}.controller")

router.get("/", getAll\${capitalized})

module.exports = router
\`

const modelContent = \`// Model for \${name}
module.exports = {}
\`

const createFile = (fileName, content) => {
  const filePath = path.join(featureDir, fileName)
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content)
    console.log("Created:", filePath)
  } else {
    console.log(filePath, "already exists, skipping")
  }
}

createFile(\`\${name}.controller.js\`, controllerContent)
createFile(\`\${name}.routes.js\`, routeContent)
createFile(\`\${name}.model.js\`, modelContent)

console.log(\`Feature "\${name}" created successfully!\`)
`
  )
  fs.chmodSync(createModuleTool, 0o755)
  console.log("Created tools/createModule.js")
}

// === deleteModule.js ===
const deleteModuleTool = path.join(toolsDir, "deleteModule.js")
if (!fs.existsSync(deleteModuleTool)) {
  fs.writeFileSync(
    deleteModuleTool,
`const fs = require("fs")
const path = require("path")

const name = process.argv[2]
if (!name) {
  console.error("Please provide a feature name. Example: node tools/deleteModule.js user")
  process.exit(1)
}

const featureDir = path.join(process.cwd(), "src", "features", name)

if (fs.existsSync(featureDir)) {
  fs.rmSync(featureDir, { recursive: true, force: true })
  console.log(\`Deleted feature folder: \${featureDir}\`)
} else {
  console.log("Feature not found, skipping...")
}
`
  )
  fs.chmodSync(deleteModuleTool, 0o755)
  console.log("Created tools/deleteModule.js")
}

console.log("Express project setup complete!")
