import fs from "fs"
import path from "path"
import { execSync } from "child_process"
import { fileURLToPath } from "url"

// === Directory setup ===
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectDir = process.cwd()
const srcDir = path.join(projectDir, "src")
const toolsDir = path.join(projectDir, "tools")

const folders = [
  "src/config",
  "src/core/middleware",
  "src/core/utils",
  "src/features",
  "tools"
]

// === Helper to run commands ===
const run = (cmd) => {
  console.log(`Running: ${cmd}`)
  execSync(cmd, { cwd: projectDir, stdio: "inherit" })
}

// === Initialize project ===
console.log("🔧 Initializing Express project...")

const pkgPath = path.join(projectDir, "package.json")
const pkgExists = fs.existsSync(pkgPath)

if (!pkgExists) {
  run("npm init -y")
} else {
  console.log("package.json exists — skipping npm init")
}

// === Install dependencies ===
if (!fs.existsSync(path.join(projectDir, "node_modules"))) {
  run("npm install express cors dotenv morgan")
} else {
  console.log("node_modules exist — skipping dependency install")
}

// === Update package.json ===
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"))

pkg.type = "module"
pkg.main = "src/server.js"
pkg.scripts = {
  dev: "node --watch src/server.js",
  models: "node tools/createModule.js",
  delete: "node tools/deleteModule.js"
}

fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2))
console.log("Updated package.json with scripts, type=module, and entry point")

// === Create folders ===
folders.forEach((dir) => {
  const fullPath = path.join(projectDir, dir)
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true })
    console.log(`Created folder: ${dir}`)
  }
})

// === .gitignore ===
const gitIgnorePath = path.join(projectDir, ".gitignore")
if (!fs.existsSync(gitIgnorePath)) {
  fs.writeFileSync(
    gitIgnorePath,
    `node_modules
.env
setUpExpress.js
`
  )
  console.log(".gitignore created")
}

// === app.js ===
const appJs = path.join(srcDir, "app.js")
if (!fs.existsSync(appJs)) {
  fs.writeFileSync(
    appJs,
`import express from "express"
const app = express()

app.use(express.json())

// Example route
app.get("/", (req, res) => {
  res.send("Server running. Generated by setup script.")
})

export default app
`
  )
  console.log("Created src/app.js")
}

// === server.js ===
const serverJs = path.join(srcDir, "server.js")
if (!fs.existsSync(serverJs)) {
  fs.writeFileSync(
    serverJs,
`import app from "./app.js"

const PORT = process.env.PORT || 3000
app.listen(PORT, () => {
  console.log(\`Server listening on port \${PORT}\`)
})
`
  )
  console.log("Created src/server.js")
}

// === createModule.js ===
const createModuleTool = path.join(toolsDir, "createModule.js")
if (!fs.existsSync(createModuleTool)) {
  fs.writeFileSync(
    createModuleTool,
`import fs from "fs"
import path from "path"

const name = process.argv[2]
const type = process.argv[3] || "all"

if (!name) {
  console.error("Please provide a feature name. Example: npm run models user")
  process.exit(1)
}

const validTypes = ["all", "controller", "routes", "model"]
if (!validTypes.includes(type)) {
  console.error(\`Invalid type "\${type}". Use one of: \${validTypes.join(", ")}\`)
  process.exit(1)
}

const capitalized = name.charAt(0).toUpperCase() + name.slice(1)
const featureDir = path.join(process.cwd(), "src", "features", name)
if (!fs.existsSync(featureDir)) fs.mkdirSync(featureDir, { recursive: true })

const controllerContent = \`export const getAll\${capitalized} = (req, res) => {
  res.send("Get all \${name}")
}\`

const routeContent = \`import express from "express"
import { getAll\${capitalized} } from "./\${name}.controller.js"

const router = express.Router()
router.get("/", getAll\${capitalized})
export default router
\`

const modelContent = \`// Model for \${name}
export default {}
\`

const createFile = (fileName, content) => {
  const filePath = path.join(featureDir, fileName)
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content)
    console.log("Created:", filePath)
  } else {
    console.log(filePath, "already exists, skipping")
  }
}

if (type === "all" || type === "controller") createFile(\`\${name}.controller.js\`, controllerContent)
if (type === "all" || type === "routes") createFile(\`\${name}.routes.js\`, routeContent)
if (type === "all" || type === "model") createFile(\`\${name}.model.js\`, modelContent)

console.log(\`Feature "\${name}" created successfully!\`)
`
  )
  fs.chmodSync(createModuleTool, 0o755)
  console.log("Created tools/createModule.js")
}

// === deleteModule.js ===
const deleteModuleTool = path.join(toolsDir, "deleteModule.js")
if (!fs.existsSync(deleteModuleTool)) {
  fs.writeFileSync(
    deleteModuleTool,
`import fs from "fs"
import path from "path"

const name = process.argv[2]
if (!name) {
  console.error("Please provide a feature name. Example: npm run delete user")
  process.exit(1)
}

const featureDir = path.join(process.cwd(), "src", "features", name)

if (fs.existsSync(featureDir)) {
  fs.rmSync(featureDir, { recursive: true, force: true })
  console.log(\`Deleted feature folder: \${featureDir}\`)
} else {
  console.log("Feature not found, skipping...")
}
`
  )
  fs.chmodSync(deleteModuleTool, 0o755)
  console.log("Created tools/deleteModule.js")
}

console.log("Express project setup complete!")
